# Generated by Django 5.1.5 on 2025-02-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='resoloved',
            new_name='resolved',
        ),
    ]
